name: koushu-alert

on:
  schedule:
    - cron: '*/30 * * * *'  # 30分ごと
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          pip install -r requirements.txt

      - run: python main.py
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
